import BN from 'bn.js';
import { Protocol, Exchange } from './types';

export const SOURCES_MAP = new Map([
  [
    Exchange.FLOWX,
    new Map([
      [Protocol.FLOWX_V2, 'FLOWX'],
      [Protocol.FLOWX_V3, 'FLOWX_CLMM'],
      [Protocol.KRIYA_DEX, 'KRIYA'],
      [Protocol.TURBOS_FIANCE, 'TURBOS'],
      [Protocol.CETUS, 'CETUS'],
      [Protocol.AFTERMATH, 'AFTERMATH'],
      [Protocol.DEEPBOOK, 'DEEP_BOOK'],
      [Protocol.KRIYA_V3, 'KRIYA_CLMM'],
      [Protocol.DEEPBOOK_V3, 'DEEPBOOK_V3'],
      [Protocol.BLUEMOVE, 'BLUEMOVE'],
      [Protocol.BLUEFIN, 'BLUEFIN'],
      [Protocol.FLOWX_PMM, 'FLOWX_PMM'],
      [Protocol.BLUEMOVE_FUN, 'BLUEMOVE_FUN'],
      [Protocol.HOP_FUN, 'HOP_FUN'],
      [Protocol.SEVEN_K_FUN, '7K_FUN'],
      [Protocol.TURBOS_FUN, 'TURBOS_FUN'],
      [Protocol.OBRIC, 'OBRIC'],
      [Protocol.HAEDAL_PMM, 'HAEDAL_PMM'],
      [Protocol.HAEDAL, 'HAEDAL'],
      [Protocol.SPRING_SUI, 'SPRING_SUI'],
      [Protocol.ALPHA_FI, 'ALPHA_FI'],
      [Protocol.VOLO_LSD, 'VOLO_LSD'],
      [Protocol.AFTERMATH_LSD, 'AFTERMATH_LSD'],
      [Protocol.STEAMM, 'STEAMM'],
      [Protocol.METASTABLE, 'METASTABLE'],
      [Protocol.MAGMA_FINANCE, 'MAGMA_FINANCE'],
      [Protocol.MOMENTUM_FINANCE, 'MOMENTUM_FINANCE'],
      [Protocol.FULL_SAIL, 'FULL_SAIL'],
      [Protocol.SEVENK_V1, 'SEVENK_V1'],
      [Protocol.IPX_TIDE, 'IPX_TIDE'],
    ]),
  ],
  [
    Exchange.AFTERMATH,
    new Map([
      [Protocol.FLOWX_V2, 'FlowX'],
      [Protocol.FLOWX_V3, 'FlowXClmm'],
      [Protocol.KRIYA_DEX, 'Kriya'],
      [Protocol.TURBOS_FIANCE, 'Turbos'],
      [Protocol.CETUS, 'Cetus'],
      [Protocol.AFTERMATH, 'Aftermath'],
      [Protocol.DEEPBOOK, 'DeepBook'],
      [Protocol.KRIYA_V3, 'KriyaClmm'],
      [Protocol.DEEPBOOK_V3, 'DeepBookV3'],
      [Protocol.BLUEMOVE, 'BlueMove'],
      [Protocol.BLUEFIN, 'Bluefin'],
      [Protocol.HOP_FUN, 'HopFun'],
      [Protocol.TURBOS_FUN, 'TurbosFun'],
      [Protocol.OBRIC, 'Obric'],
      [Protocol.SPRING_SUI, 'SpringSui'],
      [Protocol.STEAMM, 'Steamm'],
      [Protocol.METASTABLE, 'Metastable'],
      [Protocol.MAGMA_FINANCE, 'Magma'],
      [Protocol.MOMENTUM_FINANCE, 'Momentum'],
      [Protocol.FULL_SAIL, 'FullSail'],
      [Protocol.DOUBLE_UP_PUMP, 'DoubleUpPump'],
      [Protocol.MOVE_PUMP, 'MovePump'],
      [Protocol.SUISWAP, 'SuiSwap'],
      [Protocol.SUIAI, 'SuiAi'],
      [Protocol.BLASTFUN, 'BlastFun'],
    ]),
  ],
  [
    Exchange.BLUEFIN,
    new Map([
      [Protocol.FLOWX_V2, 'flowx'],
      [Protocol.FLOWX_V3, 'flowx_v3'],
      [Protocol.KRIYA_DEX, 'kriya'],
      [Protocol.TURBOS_FIANCE, 'turbos'],
      [Protocol.CETUS, 'cetus'],
      [Protocol.AFTERMATH, 'aftermath'],
      [Protocol.KRIYA_V3, 'kriya_v3'],
      [Protocol.DEEPBOOK_V3, 'deepbook_v3'],
      [Protocol.BLUEMOVE, 'bluemove'],
      [Protocol.BLUEFIN, 'bluefin'],
      [Protocol.OBRIC, 'obric'],
      [Protocol.HAEDAL_PMM, 'haedal_pmm'],
      [Protocol.SPRING_SUI, 'springsui'],
      [Protocol.STEAMM, 'steamm'],
      [Protocol.MAGMA_FINANCE, 'magma'],
      [Protocol.MOMENTUM_FINANCE, 'momentum'],
      [Protocol.FULL_SAIL, 'fullsail'],
      [Protocol.SEVENK_V1, 'sevenk_v1'],
      [Protocol.SUISWAP, 'suiswap'],
      [Protocol.BLUEFINX, 'bluefinx'],
      [Protocol.ST_SUI, 'stsui'],
    ]),
  ],
  [
    Exchange.CETUS,
    new Map([
      [Protocol.FLOWX_V2, 'FLOWX'],
      [Protocol.FLOWX_V3, 'FLOWXV3'],
      [Protocol.KRIYA_DEX, 'KRIYA'],
      [Protocol.TURBOS_FIANCE, 'TURBOS'],
      [Protocol.CETUS, 'CETUS'],
      [Protocol.AFTERMATH, 'AFTERMATH'],
      [Protocol.KRIYA_V3, 'KRIYAV3'],
      [Protocol.DEEPBOOK_V3, 'DEEPBOOKV3'],
      [Protocol.BLUEMOVE, 'BLUEMOVE'],
      [Protocol.BLUEFIN, 'BLUEFIN'],
      [Protocol.OBRIC, 'OBRIC'],
      [Protocol.HAEDAL_PMM, 'HAEDALPMM'],
      [Protocol.SPRING_SUI, 'SPRINGSUI'],
      [Protocol.STEAMM, 'STEAMM'],
      [Protocol.MAGMA_FINANCE, 'MAGMA'],
      [Protocol.MOMENTUM_FINANCE, 'MOMENTUM'],
      [Protocol.SEVENK_V1, 'SEVENK'],
      [Protocol.HAEDAL, 'HAEDAL'],
      [Protocol.METASTABLE, 'METASTABLE'],
      [Protocol.ALPHA_FI, 'ALPHAFI'],
      [Protocol.AFSUI, 'AFSUI'],
      [Protocol.VOLO_LSD, 'VOLO'],
      [Protocol.SCALLOP, 'SCALLOP'],
      [Protocol.FULL_SAIL, 'FULLSAIL'],
      [Protocol.HAEDALHMMV2, 'HAEDALHMMV2'],
      [Protocol.HAWAL, 'HAWAL'],
    ]),
  ],
]);

export const BPS = new BN(1_000_000);
